hosts:
  - peterwilsoncc.local
  - peterwilsonme.local
  - vagrant.local

extensions:
  - Chassis/tester
  - Chassis/cavalcade
  - Chassis/mailhog
  - Chassis/xdebug
  - Chassis/memcache
  - Chassis/tachyon
  - Chassis/fakes3

php: 7.2
